### PR TITLE
Pull request for #34: Adds State of Repo Logger

### PR DESCRIPTION
**Pull request by lboxell**
@yuchuan2016, can you PR this and https://github.com/gslab-econ/template/pull/32 together?

One thing I was unsure about is whether the state_of_repo logger should go in misc.py or the builders. Technically, we use it as a builder, but it really is more of a 'misc' type of function that we use and don't expect the end user to modify.

### CODE REVIEW

**Comment by yuchuan2016** [comment]
@lboxell , nice work! I think it's fine to store it in `misc`. Do you think it would be helpful to add `maxit` as an option that allows users to specify?

**Comment by lboxell** [comment]
@yuchuan2016,

I added the maxit option and updated the template accordingly. I also merged master into this branch. Let me know if there is anything else.

**Comment by yuchuan2016** [comment]
Hi @lboxell , I run the template on my PC, and files like `.\.gitattributes` are also recorded. Would you add
`re.search('\.\\.', os.path.join(root, name))` besides `re.search('\./\.', os.path.join(root, name))`?

**Comment by lboxell** [comment]
@yuchuan2016,

I made the edit. Let me know if it works now.

**Comment by yuchuan2016** [comment]
@lboxell , it works! Feel free to merge.

**Pull request merged**
