### PR TITLE
Pull request for #26: Allow CL arguments to be passed

### PR DESCRIPTION
**Pull request by lboxell**
See https://github.com/gslab-econ/template/tree/gslab_python-issue26_clarg for where I was testing this code.

### CODE REVIEW

**Comment by lboxell** [comment]
@arosenbe, 

I've updated the unit tests. One of the release_tools tests still fails for me and I'm not sure what the issue is. Given there are other tasks open regarding the release module and refactoring the unit tests, I'm inclined to leave as-is (or have someone who knows what is going on with those tests take a look at it). 

My thoughts are that I'll update the template once I've updated the new gslab_scons module in master.

**Comment by lboxell** [comment]
@arosenbe,

Just checking in on this.

**Comment by arosenbe** [comment]
@lboxell, sorry for the delay. 

I reran the tests after reinstalling a clean version of `gslab_scons` and didn't get any errors. Any thoughts on why you would have some that I wouldn't.

Your plan with the template sounds fine.

**Comment by lboxell** [comment]
I updated my mock installation and re-ran the tests successfully.

I'm going to merge this branch now.

**Comment by arosenbe** [comment]
@lboxell, it looks like you didn't make a release with the change. Could you?

**Comment by lboxell** [comment]
Done.

**Pull request merged**
