### PR TITLE
4.0.0 Release

### PR DESCRIPTION
**Pull request by stanfordquan**
### Features
 - Adds configuration tests to test for proper dependency installation ([gslab-econ/template#43](https://github.com/gslab-econ/template/issues/43), #66)
 - Allows custom `release` destination (#68, #72)
 - Allows tablefill builder to use `.tex` files in addition to .lyx (#73, #82)

### Bugs
 - Edited `release` tools to improve size warnings (#59, #60)
 - Fixes R builder's command line arguments (#58, #65)
 - Fixes sconstruct logging to create individual files instead of overwriting (#77, #80)

### Misc
 - Reorganized source code, improved logging (#28, #47)
 - Improves warnings on time-log failure (#58, #65)
 - Improves logging on tablefill builder (#69, #70)
 - Adds traceback printing for Python builder (#75, #76)
 - Standardized Stata executable naming (gslab-econ/template#45, #67)
 - Readme updates ([here](https://github.com/gslab-econ/gslab_python/pull/81/commits/6ed0f5e5f197c8b0690a286f9076f8ff625ef8fe), [here](https://github.com/gslab-econ/gslab_python/pull/81/commits/cd3200e27cc0d2c87ad27181ed01c8596463d44c), [here](https://github.com/gslab-econ/gslab_python/pull/81/commits/7ea9a9f4002bde9ca96433a76bf096635f1f349e), and [here](https://github.com/gslab-econ/gslab_python/pull/81/commits/0b188445110b11e213e5495c2ce756110459b943))

<details>
    <summary>preliminary version: more verbose release notes </summary>
# GSLab Python 4.0.0 Release Notes

Welcome to the `gslab_python` version 4.0.0. These are the changes from 

### Requirements for default template

- We no longer require R and GSLab-modified Metropolis beamer theme to run the default template. `gslab_python` still support them. 

- We now require `yaml` parsers for Python and Stata ([PyYAML](http://pyyaml.org/wiki/PyYAML), [Stata yaml](https://github.com/gslab-econ/stata-misc))

### SConstruct

- We now run a **configuration test** at the beginning of each SConstruct. The default `configuration_test.py` check that the following software packages are installed and present in the `PATH` environment variable: Python (pkgs `yaml`, `gslab_scon`, `gslab_fill`), Lyx, Git LFS, Stata (pkg `yaml`; see **Stata** for more information). The test will also check whether cache and release directories are correctly specified, if applicable. 

- Constants such as paths, executables, and other environment variables can now be loaded using **constants.yaml** and **user-config.yaml**. `SConscript` and analysis scripts contain examples of how to load constants. The user will be prompted for missing values in the `yaml` files if the script needs them.

- A run of SCons now will produce a *debriefing* into `state_of_repo.log`. 

- **Size warning** [in progress] 

### Logging 

- After a run of SCons, `SConstruct.log` will contain (in order):
	- The top level SCons output
	- Builder logs (a.k.a. `SConscript*.log` files) that resulted in an error or were incomplete
	- Builder logs that were created during this SCons run. 

- Each builder will automatically produce a **builder log** (a.k.a. `SConscript*.log` files) in the directory of the first listed target. The user can specify an extension to the name of the log file (the `*` in `SConscript*.log`) by way of a `log_ext = *` argument when calling the builder. 

- Completed logs now have **start/end timestamps** at the top. Logs are decorated to distinguish the timestamps and between between logs appended to `SConstruct.log`. We also circulate a Sublime Text syntax highlighting theme to help make logs more readable. 

### Stata

- The user will specify in **user-config.yaml** the name of the Stata executable on their system (e.g. what they use to call Stata on the command line). There is an option to enter nothing and leave it blank, at which point the builder will attempt to call Stata using common executable names (`%%STATAEXE%%` and `StataMP-64.exe` on Windows, `stata-mp`, `stata-se`, and `stata` on Mac OS).

### Command line arguments

IPR @arosenbe help me out here

### Release 

- The full path of the release drive can be specified in `user-config.yaml`.

- **Inspect repo**  @lboxell  

## Misc notes

- *Debriefing* and *logging* functionalities are supported by the Python package `atexit` which runs Python scripts at the conclusion of a Python process (being `SCons` for our purposes).

- Errors raised in the execution of a builder are raised as an `ExecCallError`. In general, failures in a Stata script are not recorded as a builder failure, so this error will not be raised. An error in a Python script will be raised as an `ExecCallError` with the traceback printed out along with the error raised within the subprocess. 

- The README is now prettier. Output is also a lot prettier and more informative.

- Scripts are extensively tested using `mock`. 

</details>

### CODE REVIEW

**Comment by stanfordquan** [comment]
@arosenbe @lboxell this is the only task left before we ping PIs about this release, so I would appreciate it if you guys can help fill in the `in progress` bits above (where I think you guys have comparative advantage in completing them) soon so that PIs can take a look. Thanks!

**Comment by lboxell** [comment]
Per @arosenbe's suggestion of looking at [git-lfs' changelogs](https://github.com/git-lfs/git-lfs/blob/master/CHANGELOG.md) and [here](https://github.com/git-lfs/git-lfs/releases/tag/v2.0.0), we might want to substantially pare down the narrative and just provide a link to the relevant location (task) where the change was made.  A sentence per task seems like it would be sufficient. 

The git-lfs change logs look very similar to our commit history (see [here](https://github.com/gslab-econ/gslab_python/pull/81/commits)). The squash-and-merge protocol makes things nearly self-documenting (if we were stricter on the protocol and more careful with the pull request titles, we could probably just point to the commit history as the change log and perhaps just highlight a few "key" things).

**Comment by lboxell** [comment]
@stanfordquan @arosenbe, See my change log proposal above.

**Comment by arosenbe** [comment]
Clean, simple, and seems accurate, looks good to me!

**Comment by stanfordquan** [comment]
I'm good with this style. @arosenbe do you have any more comment before we ping PIs?

**Comment by stanfordquan** [comment]
@gentzkow @jmshapir we prepared the release notes for gslab_python 4.0.0 [at the top of this pull request](https://github.com/gslab-econ/gslab_python/pull/81#issue-244890080). Please let us know what we can do to facilitate your review. Thanks!

Companion pull request at template [here](https://github.com/gslab-econ/template/pull/52).

**Comment by jmshapir** [comment]
Thanks @stanfordquan, happy to defer to @gentzkow here.

**Comment by gentzkow** [comment]
@stanfordquan Thanks! Procedural question: I think we will want to do a comprehensive look at the Python library and template and develop a plan for next steps. Do you think that should be in the scope of this pull request? Or should I limit this to deciding whether this version is ready for release and we can open a separate task for the larger review?

**Comment by gentzkow** [comment]
@stanfordquan Also: What is the recommended way to test `template` with `gslab_python 4.0` prior to the latter being actually released? Should I install the latter from the dev branch? Or point to it locally in some other way?

**Comment by stanfordquan** [comment]
@gentzkow , please install `gslab_python` from the development branch `dev_four` using `python setup.py install clean`, and test `template` from its development branch (also named `dev_four`)

**Comment by stanfordquan** [comment]
@gentzkow my opinion is that we should release this if you think it has met the objectives from the last meetings. Whether you want to do a "next steps" review is up to if it's more convenient for you.

**Comment by gentzkow** [comment]
@stanfordquan Is there a summary where we collected notes from those last meetings? I know we have a lot of discussion in the thread of [template-#19](https://github.com/gslab-econ/template/issues/19) but I can't remember if we have a compact summary somewhere.

**Comment by stanfordquan** [comment]
@gentzkow  I'm afraid we don't have a more compact summary than that (beyond the issues that were opened in reference to that task). The RAs also had a separate meeting in April, the notes of which are summarized [here](https://github.com/gslab-econ/gslab_python/issues/58#issuecomment-295959587).

**Comment by gentzkow** [comment]
@stanfordquan I have posted my comments on my overall review in the parallel task at [template-#52](https://github.com/gslab-econ/template/pull/52).

The only additional note is that Github appears to have a bunch of automated code checks that run and indicate ways our code could be improved (see "All checks have failed" in this thread). I would propose that we clean up the code so these do not fail.

Otherwise, cleared to release.

(If we think cleanup is going to be a big task we could release first then make the cleanup an update.)

**Comment by lboxell** [comment]
@gentzkow,

Regarding the automated code review, that was something I was just testing out today. It's a github integration that lets you define code style parameters that get automatically checked. If you click "details" where it says "Not so good... This pull request quality could be better.", it shows you an automated set of comments based on your defined style for a given language. It also gives you other information such as duplicated code blocks, etc.  It seems like this sort of thing could be useful to limit the basic style comments in peer review so the peer reviewer can focus on more substantive issues (particularly for new lab members). 

If we decide we want to use something like this, then we'll want to fine tune the style checks.

Drawbacks:
 - Its only free for open-source repositories.
 - I don't think it has R or Stata support (there may be another company that does these but I'm not sure). So, we'd just be using it for python. 


I'll remove the integration for now, and we can evaluate using it later (I'll put on the admin outline, unless you think something else should be done with it.).

**Comment by gentzkow** [comment]
Ok

Just to be sure: Should we look at these comments and decide which would
improve the code to incorporate?

**Comment by lboxell** [comment]
@gentzkow, That probably would be a good idea.
@stanfordquan, FYI.

---



On Jul 27, 2017, at 1:17 AM, Matthew Gentzkow <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok

Just to be sure: Should we look at these comments and decide which would
improve the code to incorporate?

**Comment by stanfordquan** [comment]
That's a wrap. [Companion PR in `template` pulled in.](https://github.com/gslab-econ/template/pull/52)

**Comment by stanfordquan** [comment]
See release [here](https://github.com/gslab-econ/gslab_python/tree/v4.0.0).

**Pull request merged**
