### PR TITLE
Pull request for #23: Create Lyx scanner

### PR DESCRIPTION
**Pull request by yuchuan2016**
@lboxell , this pull request comes together with gslab-econ/template#29.

### CODE REVIEW

**Comment by lboxell** [comment]
@yuchuan2016,

 I think we need to write a unit test for the new function, but otherwise, it looks good. I made a small edit to fix the error with the stata_command_* functions.

**Comment by yuchuan2016** [comment]
@lboxell , thanks! I have a small question about the unit test. Since the new function takes an argument `node`, which has a method `get_contents`, i.e., 
`contents = node.get_contents()`

Should we define a new class `node` in the unit test and `get_contents` a method of it?

**Comment by lboxell** [comment]
I think the mock module will allow testing without creating the node class. I don't know much about the mock module though, but you can probably ask @stanfordquan tomorrow.

--



On Jan 24, 2017, at 7:41 PM, chuanyu <notifications@github.com<mailto:notifications@github.com>> wrote:


@lboxell<https://github.com/lboxell> , thanks! I have a small question about the unit test. Since the new function takes an argument node, which has a method get_contents, i.e.,
contents = node.get_contents()

Should we define a new class node in the unit test and get_contents a method of it?

-

**Comment by lboxell** [comment]
As a note, I saw [this](https://bitbucket.org/scons/scons/src/71f7dfac569a24b5b930f86f118c045198ad82fd/src/engine/SCons/Scanner/LaTeX.py?at=default&fileviewer=file-view-default) when I was working on another task. I think what we currently have works well (and is substantially simpler), but there might be some utility in this Latex scanner that we'll want to implement at some point.

**Comment by yuchuan2016** [comment]
Hi @lboxell ,

Credit to @M-R-Sullivan , the unit test for the function `lyx_scan` is added. Tell me if you have any questions, or I will merge it to `master`.

**Comment by lboxell** [comment]
@yuchuan2016,

Looks good. Feel free to merge.

**Pull request merged**
