### PR TITLE
Pull request for #146: make_list_if_string-related bug

### PR DESCRIPTION
**Pull request by arosenbe**
@stanfordquan, can you review my fix in #146. I added a check if the `source` argument evaluates to `False`. If so, then we set the source to `''`.  Otherwise, we continue as we did before. 

I also added quoting around the source file to handle the type of issue you raised in #147.

### CODE REVIEW

**Comment by stanfordquan** [comment]
@arosenbe I just found this issue so I'm documenting it here. I haven't checked it out on this PR yet, but FYI.

In `build_anything`, `source = ['']` defaults `source` to the folder the SConscript is in.

```
analysis (master)$ python run.py
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
execute_system_call(["build/prepare_data/data.txt"], ["source/prepare_data"])
scons: `release' is up to date.
scons: done building targets.
analysis (master)$ git diff source/
diff --git a/analysis/source/prepare_data/SConscript b/analysis/source/prepare_data/SConscript
index 88852c6..0638341 100644
--- a/analysis/source/prepare_data/SConscript
+++ b/analysis/source/prepare_data/SConscript
@@ -4,9 +4,9 @@ import gslab_scons as gs
 build  = env['CONFIG']['global']['build']['prepare_data']
 source = env['CONFIG']['global']['source']['prepare_data']

-env.BuildPython(target  = ['#%s/data.txt'       % build],
-                source  = ['#%s/create_data.py' % source],
-                log_ext =  'create_data')
+# env.BuildPython(target  = ['#%s/data.txt'       % build],
+#                 source  = ['#%s/create_data.py' % source],
+#                 log_ext =  'create_data')

 # env.BuildStata(target  = ['#%s/data.txt'       % build],
 #                source  = ['#%s/create_data.do' % source],
@@ -21,10 +21,10 @@ env.BuildPython(target  = ['#%s/data.txt'       % build],
 #                 log_ext =  'create_data')

 # # Invalid syntax for Windows.
-# gs.build_anything(target  = ['#%s/data.txt' % build],
-#                   source  = [''],
-#                   action  = 'sh source/prepare_data/create_data.sh',
-#                   log_ext = 'create_data',
-#                   env     = env)
+gs.build_anything(target  = ['#%s/data.txt' % build],
+                  source  = [''],
+                  action  = 'sh source/prepare_data/create_data.sh',
+                  log_ext = 'create_data',
+                  env     = env)

 env.Install('#release/lg', '#%s/data.txt' % build)
```

**Comment by arosenbe** [comment]
Thanks @stanfordquan! I think the commit above takes care of this. The solution is to remove all the stuff that evaluates to False in the source and target lists before creating the Builder object. I tested this in template, but it'd be very nice to have your confirmation that it works in practice. 

I also tackled a similar issue where we were printing `execute_system_call` in place of `build_anything`. This was as simple as renaming a method.

**Comment by arosenbe** [comment]
@stanfordquan, 

1. I didn't mean to introduce wrapping around the CL args (stray code). I've removed that. As I wrote [above](https://github.com/gslab-econ/gslab_python/pull/148#issuecomment-389751983), I tested in template, and didn't find any errors. But it'd be great to have confirmation in your environment where you noticed the bug. 
2. There's no need to wrap target_dir because it isn't directly used when we execute the system call (I think, please confirm). Like I said above, I implemented quote-wrapping around the log file in #147 [(code)](https://github.com/gslab-econ/gslab_python/blob/issue147_targetspace/gslab_scons/builders/gslab_builder.py#L78). Did you mean something else?

**Comment by stanfordquan** [comment]
We've agreed to implement the quote-wrapping around system calls rather than objects stored within the builder. That means I can pull this in with above changes, block #149 , and implement the quote-wrapping in #147 .

**Pull request merged**
